### PR TITLE
added samuel's Fact card

### PR DESCRIPTION
**Pull request by Samueljr-web**

### CODE REVIEW

**Comment by DeveloperAspire** [comment]
Thank you for your contribution Samuel

**Comment by Samueljr-web** [comment]
thanks bro at least have learnt how to make pull request

**Comment by DeveloperAspire** [comment]
You are welcome Samuel, I am glad you learned that. You can check the live site here:  [DevFact](https://devfact.vercel.app/) and see your contribution. I am sure you must be very proud of yourself, because I am

**Comment by Samueljr-web** [comment]
ok bro, once again thank you bro🤪

**Comment by Samueljr-web** [comment]
hello good day bro,
bro pls is there any way I can message you directly maybe on WhatsApp or on
Facebook

drop number of FB name

**Comment by Samueljr-web** [comment]
.....................................

Adeyemi would like to stay in touch on LinkedIn.

Adeyemi Samuel
--Frontend developer || HTML | CSS | JS | REACTJS - NEXT.JS
Nigeria

View profile https://www.linkedin.com/comm/in/adeyemi-samuel-382690206?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-373-null-null-%7E4hxxbe%7Ekyfvakzm%7Ebf-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BCfJZlLNeTGq6I380Sjq%2FPA%3D%3D

Confirm that you know Adeyemi https://www.linkedin.com/e/v2?e=-4hxxbe-kyfvakzm-bf&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BCfJZlLNeTGq6I380Sjq%2FPA%3D%3D&t=suwj&tracking=eml-guest-invite-cta&ek=email_m2g_invite_single_01&validationToken=PHbwrFJi&invitationId=6888109993778913280


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-4hxxbe-kyfvakzm-bf&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=381&m=unsub&ts=unsub&loid=AQEQyEjgzTnm3wAAAX5d7sc0IP0fbV0fthhoIW0gKnQD-9wAJhcOzn9j8JkdegOusPdW8VPQcsW7VEUBIQH-zkOdemLXmy5fXRUnj-Fy8N6dc3USusmEjRj_meM8UPOJjFzOvrq2jZvYHcA2kk4PqC_5Qfr3ZeQXFQ&eid=-4hxxbe-kyfvakzm-bf

Help: https://www.linkedin.com/e/v2?e=-4hxxbe-kyfvakzm-bf&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BCfJZlLNeTGq6I380Sjq%2FPA%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=380&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to ***@***.***

© 2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request merged**
