### PR TITLE
updated the index.html and the img folder

### PR DESCRIPTION
**Pull request by tech-doctor**
i included my picture in the image folder at isaac.jpg,  and included my fact-card at 'ISAAC'S SECTION' of the index.html file

### CODE REVIEW

**Comment by DeveloperAspire** [comment]
You have a conflicting file please resolve

**Comment by tech-doctor** [comment]
> You have a conflicting file please resolve

Done

**Comment by DeveloperAspire** [comment]
Good job Isaac. Thank you for your contribution

**Comment by DeveloperAspire** [comment]
Please fix your image and write "Frontend Engineer" instead of "ReactJs Software Developer"

**Pull request merged**
